from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Iterable

import xlsxwriter

DISPLAY_COLUMNS = [
    ("recommendation", "Priority", 16),
    ("score", "Score", 8),
    ("title", "Title", 42),
    ("company", "Company", 30),
    ("location", "Location", 24),
    ("application_deadline", "Deadline", 13),
    ("application_status", "Status", 18),
    ("source", "Source", 28),
    ("seen_status", "Seen status", 20),
    ("url", "URL", 48),
]


def _read_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _is_madrid_needs_detail(row: dict) -> bool:
    source = str(row.get("source") or "").strip().casefold()
    recommendation = str(row.get("recommendation") or "").strip().upper()
    return recommendation == "NEEDS_DETAIL_REVIEW" and source.startswith("madrid i+d+i".casefold())


def _write_jobs_sheet(workbook, name: str, rows: Iterable[dict], header_fmt, text_fmt, score_fmt, link_fmt) -> None:
    rows = list(rows)
    ws = workbook.add_worksheet(name[:31])
    ws.freeze_panes(1, 0)
    for col, (_, label, width) in enumerate(DISPLAY_COLUMNS):
        ws.write(0, col, label, header_fmt)
        ws.set_column(col, col, width)
    for r, row in enumerate(rows, start=1):
        for c, (key, _, _) in enumerate(DISPLAY_COLUMNS):
            value = row.get(key, "")
            if key == "score":
                try:
                    ws.write_number(r, c, float(value), score_fmt)
                except (TypeError, ValueError):
                    ws.write(r, c, value, text_fmt)
            elif key == "url" and value:
                try:
                    ws.write_url(r, c, value, link_fmt, string=value)
                except Exception:
                    ws.write(r, c, value, text_fmt)
            else:
                ws.write(r, c, value, text_fmt)
    if rows:
        ws.autofilter(0, 0, len(rows), len(DISPLAY_COLUMNS) - 1)
    ws.set_default_row(20)


def build_report(out_dir: Path, xlsx_path: Path) -> Path:
    summary = _load_json(out_dir / "run_summary.json")
    current = _read_csv(out_dir / "actionable.csv")
    today = _read_csv(out_dir / "daily_actionable.csv")
    primary = _read_csv(out_dir / "actionable_primary.csv")
    low = _read_csv(out_dir / "actionable_low.csv")
    needs_detail_all = _read_csv(out_dir / "needs_detail_review.csv")
    madrid_needs_detail = [row for row in needs_detail_all if _is_madrid_needs_detail(row)]
    needs_detail = [row for row in needs_detail_all if not _is_madrid_needs_detail(row)]
    source_rows = _read_csv(out_dir / "source_summary.csv")

    xlsx_path.parent.mkdir(parents=True, exist_ok=True)
    workbook = xlsxwriter.Workbook(xlsx_path)
    workbook.set_properties({
        "title": "Job Search Bot Daily Report",
        "subject": "Production job-search results",
        "comments": f"Generated by {summary.get('production_version', '')}",
    })

    title_fmt = workbook.add_format({"bold": True, "font_size": 16})
    section_fmt = workbook.add_format({"bold": True, "font_size": 11, "bottom": 1})
    header_fmt = workbook.add_format({"bold": True, "border": 1, "text_wrap": True, "valign": "vcenter"})
    text_fmt = workbook.add_format({"text_wrap": True, "valign": "top"})
    score_fmt = workbook.add_format({"num_format": "0", "valign": "top"})
    link_fmt = workbook.add_format({"font_color": "blue", "underline": True, "text_wrap": True, "valign": "top"})
    int_fmt = workbook.add_format({"num_format": "0"})

    ws = workbook.add_worksheet("SUMMARY")
    ws.set_column("A:A", 34)
    ws.set_column("B:B", 18)
    ws.write("A1", "Job Search Bot — Daily Report", title_fmt)
    ws.write("A3", "Run", section_fmt)
    run_rows = [
        ("Production version", summary.get("production_version", "")),
        ("Date", summary.get("availability_as_of", "")),
        ("Configured sources", len(summary.get("configured_sources") or [])),
        ("Raw jobs", summary.get("raw", 0)),
        ("Canonical jobs", summary.get("unique", 0)),
        ("Current actionable", summary.get("current_actionable", 0)),
        ("Today's actionable", summary.get("daily_actionable", 0)),
        ("New actionable", summary.get("new_actionable", 0)),
        ("Changed/reopened actionable", summary.get("changed_or_reopened_actionable", 0)),
        ("Needs detail review — total", summary.get("needs_detail_review", 0)),
        ("Needs detail — other sources", len(needs_detail)),
        ("Madrid needs detail", len(madrid_needs_detail)),
        ("State jobs", summary.get("seen_state_jobs", 0)),
        ("Errors", len(summary.get("errors") or [])),
        ("Warnings", len(summary.get("warnings") or [])),
    ]
    for idx, (label, value) in enumerate(run_rows, start=3):
        ws.write(idx, 0, label)
        if isinstance(value, int):
            ws.write_number(idx, 1, value, int_fmt)
        else:
            ws.write(idx, 1, value)

    rec = summary.get("recommendations") or {}
    start = 20
    ws.write(start, 0, "Recommendations", section_fmt)
    for i, key in enumerate(("STRONG_APPLY", "APPLY", "REVIEW", "LOW_PRIORITY", "SKIP"), start=start + 1):
        ws.write(i, 0, key)
        ws.write_number(i, 1, int(rec.get(key, 0) or 0), int_fmt)

    source_status = {"OK": 0, "PARTIAL": 0, "ERROR": 0}
    for row in (summary.get("source_runs") or {}).values():
        status = str(row.get("status") or "ERROR").upper()
        source_status[status if status in source_status else "ERROR"] += 1
    start2 = 28
    ws.write(start2, 0, "Source health", section_fmt)
    for i, key in enumerate(("OK", "PARTIAL", "ERROR"), start=start2 + 1):
        ws.write(i, 0, key)
        ws.write_number(i, 1, source_status[key], int_fmt)

    _write_jobs_sheet(workbook, "TODAY_ACTIONABLE", today, header_fmt, text_fmt, score_fmt, link_fmt)
    _write_jobs_sheet(workbook, "CURRENT_ACTIONABLE", current, header_fmt, text_fmt, score_fmt, link_fmt)
    _write_jobs_sheet(workbook, "PRIMARY", primary, header_fmt, text_fmt, score_fmt, link_fmt)
    _write_jobs_sheet(workbook, "LOW_PRIORITY", low, header_fmt, text_fmt, score_fmt, link_fmt)
    _write_jobs_sheet(workbook, "NEEDS_DETAIL", needs_detail, header_fmt, text_fmt, score_fmt, link_fmt)
    _write_jobs_sheet(workbook, "MADRID_NEEDS_DETAIL", madrid_needs_detail, header_fmt, text_fmt, score_fmt, link_fmt)

    src = workbook.add_worksheet("SOURCES")
    source_cols = [
        ("source_key", "Key", 18), ("source", "Source", 34), ("status", "Status", 12),
        ("canonical_jobs", "Canonical", 12), ("actionable", "Actionable", 12),
        ("detail_success", "Detail OK", 12), ("detail_failed", "Detail failed", 14),
        ("coverage_complete", "Coverage complete", 18), ("error", "Error", 36), ("warnings", "Warnings", 42),
    ]
    for c, (_, label, width) in enumerate(source_cols):
        src.write(0, c, label, header_fmt)
        src.set_column(c, c, width)
    for r, row in enumerate(source_rows, start=1):
        for c, (key, _, _) in enumerate(source_cols):
            src.write(r, c, row.get(key, ""), text_fmt)
    src.freeze_panes(1, 0)
    if source_rows:
        src.autofilter(0, 0, len(source_rows), len(source_cols) - 1)

    workbook.close()
    return xlsx_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a compact production XLSX report from live_output")
    parser.add_argument("--out-dir", default="live_output")
    parser.add_argument("--xlsx", default="live_output/job_search_report.xlsx")
    args = parser.parse_args()
    path = build_report(Path(args.out_dir), Path(args.xlsx))
    print(path)


if __name__ == "__main__":
    main()
